-- 작성자 : 이광호

--1)

CREATE TABLE tbl_product#(
	PCODE varchar2(20) NOT NULL PRIMARY KEY,
	CATEGORY char(2),
	PNAME nvarchar2(20) NOT NULL,
	PRICE number(9) NOT NULL
	);

CREATE TABLE tbl_custom#(
	CUSTOM_ID varchar2(20) NOT NULL PRIMARY KEY,
	NAME nvarchar2(20) NOT NULL,
	EMAIL varchar2(30),
	AGE number(3),
	REG_DATE timestamp
	);

CREATE TABLE tbl_buy#(
	BUY_SEQ NUMBER(8) NOT NULL PRIMARY KEY,
	CUSTOM_ID varchar2(20),
	PCODE varchar2(20),
	QUANTITY number(5) NOT NULL,
	BUY_DATE timestamp,
	FOREIGN KEY(PCODE) REFERENCES tbl_product#(PCODE),
	FOREIGN KEY(CUSTOM_ID) REFERENCES tbl_custom#(CUSTOM_ID)
	);

--2)

CREATE SEQUENCE tbl_buy_seq START WITH 2001;

--3)

CREATE TABLE TBL_POSTCODE(
	POSTCODE char(6) NOT NULL PRIMARY KEY,
	AREA1 varchar2(200) NOT null
	);

--4)

ALTER TABLE TBL_CUSTOM# ADD POSTCODE char(6);
	
--5)

ALTER TABLE TBL_CUSTOM# ADD CONSTRAINT TBL_CUSTOM#_fk
FOREIGN key(POSTCODE) REFERENCES TBL_POSTCODE(POSTCODE);

